/** Plain-English definitions used for column tooltips and the Glossary page. */
export const G: Record<string, string> = {
  distress_event: 'The first quarter a borrower\'s mark (summed across every lender) drops below 0.90 or any lender puts it on non-accrual, after having been above 0.90 and accruing the quarter before.',
  neighbor: 'A borrower still marked at 0.97 or better whose profile (lien, rate, spread, PIK, months to maturity, size, number of lenders, sector where known) is closest to what a borrower that just went bad looked like the quarter before it went bad.',
  neighbor_distance: 'How far apart two borrowers\' profiles are, in standard deviations per feature, averaged over the features both have. 0.5 is a close match; above 1.5 is a loose one.',
  asset_coverage: 'Total assets minus non-debt liabilities, divided by debt: (net assets + debt) / debt. BDCs must keep it above 150%. Below that they cannot borrow more or pay dividends, so they must raise equity or sell loans.',
  coverage_distance: 'How many percentage points of asset coverage the BDC has above the 150% minimum. 20 points means coverage of 170%.',
  forced_seller: 'Flag: within 20 points of the 150% asset-coverage minimum AND the share of loans below 90 rose in each of the last two quarters. A BDC in that spot has little room to absorb more markdowns and may have to sell loans to stay compliant.',
  turnover: 'Share of each side\'s book replaced from one quarter to the next. 0.25 means a quarter of the names changed. Higher turnover means more trading cost.',
  borrow_cost: 'What it costs to borrow shares to short, per holding period. Charged at 15% a year for names trading under $1m a day, 5% for $1m to $5m, 1% above $5m. Small BDCs are expensive to short.',
  liquidity_floor: 'The minimum median daily dollar volume a name must trade for the strategy to hold it. Ranks are computed against every liquid BDC; the floor only changes which names can be in the book.',
  residual_score: 'The health score with the part explained by price / NAV removed, by regressing one on the other across BDCs each quarter. Tests whether the score carries information the market price does not already reflect.',
  conviction: 'Position sizes in proportion to how far a name\'s score sits from the middle of the pack, instead of equal dollars. The strongest calls get the most money.',
  risk_wf: 'The loan warning score rolled up per BDC, refitted every quarter on loan-quarters whose one-year outcome was already known on the scoring date, so nothing from the future leaks in. Reported as the cost-weighted average score and the share of cost scored 30 or more.',
  mark_gap: 'On a borrower held by two or more BDCs, the highest lender\'s mark minus the lowest, for the same lien type. A wide gap means at least one lender is wrong, and one of them is usually late.',
  stale_generosity: 'A BDC\'s cost-weighted mark on the borrowers it shares with other BDCs, minus what those other lenders mark the same loans. +0.02 means it carries shared loans two cents above the others.',
  no_second_opinion: 'Share of a BDC\'s debt book, at cost, in borrowers no other BDC holds. Those marks cannot be checked against anyone; the higher this is, the more you are trusting one valuation committee.',
  bdc: 'Business development company: a listed company whose business is lending to mid-sized private companies. Think of it as a fund of loans that trades like a stock.',
  mark: 'Fair value divided by cost, in cents on the dollar. 1.00 means the lender expects to be repaid in full; 0.90 means it expects to lose about 10%.',
  fair_value: 'The lender\'s own estimate of what the loan is worth today. Loans do not trade, so this is an opinion, updated every quarter.',
  cost: 'What the lender paid to make or buy the loan (principal minus upfront fees). Also called amortized cost.',
  principal: 'The amount the borrower owes.',
  nonaccrual: 'The lender has stopped counting interest as income because it doubts it will be paid. The formal "this loan is in trouble" label.',
  pik: 'Payment in kind: interest added to the loan balance instead of paid in cash. Usually means the borrower cannot afford cash interest.',
  spread: 'The lender\'s margin over the base rate (SOFR). A loan at SOFR + 5.75% has a 5.75% spread.',
  spread_up: 'The spread rose since last quarter, which almost always means the loan was amended after the borrower broke a covenant.',
  extended: 'The maturity date moved out by more than 45 days ("amend and extend").',
  debt_below_90: 'Share of the lender\'s loans (by cost) marked below 90 cents on the dollar. Loans the lender itself expects to lose 10% or more on.',
  debt_below_95: 'Share of loans (by cost) marked below 95. Stressed loans.',
  health: 'The default strategy\'s score: the average of the BDC\'s peer-rank on four things from its own loan schedule (share of loans below 90, share below 95, average mark, and NAV change over a year). 1.0 would be the healthiest book on every measure, 0 the sickest. The top fifth is the long book, the bottom fifth the short book.',
  strategy_side: 'Long: in the healthiest fifth of liquid public BDCs on the health score. Short: in the sickest fifth. Blank: the middle, no position.',
  new_deterioration: 'Share of loans (by cost) that crossed below 95 this quarter. Fresh trouble, not old news.',
  debt_mark: 'Average mark of all loans, weighted by cost. Fair value of debt divided by cost of debt.',
  quality: 'Cross-sectional z-score: how many standard deviations worse than the average BDC this quarter, across stressed, non-accrual, PIK and newly deteriorating debt. Higher is worse. 0 is average.',
  trend: 'Quality score now minus four quarters ago. Positive means the book got worse over the past year.',
  validated: 'Like the quality score, but each input is weighted by how well it predicted the next year\'s NAV change in our own backtest. Higher is worse.',
  risk: 'Estimated probability (0 to 100) that the loan goes on non-accrual, is marked below 80, or exits at a loss within four quarters. Fitted on this database\'s history. 100 means it already has.',
  generosity: 'On borrowers held by several BDCs, how far this lender\'s marks sit above (positive) or below (negative) the other lenders\' marks. Positive suggests its NAV is overstated.',
  mark_vs_peers: 'This lender\'s mark minus the average mark of the other lenders holding the same borrower.',
  nav: 'Net asset value per share: everything the BDC owns at fair value, minus what it owes, divided by shares. Its book value per share.',
  p_nav: 'Share price divided by NAV per share. Below 1.0 the market values the loans below what the BDC claims; above 1.0 it pays a premium.',
  ret: 'Total return including dividends, which for BDCs are about 9 to 10% a year.',
  div_yield: 'Dividends paid over the last 12 months divided by the share price.',
  nav_chg: 'Change in NAV per share over four quarters. Falling NAV means losses are being recognized.',
  short_score: 'Sum of four percentile ranks: worse book, worsening book, richer price to NAV, and price not yet lagging. Higher is a stronger short case.',
  long_score: 'Sum of three percentile ranks: cleaner book, improving book, cheaper price to NAV. Higher is a stronger long case.',
  quadrant: 'Short candidate: worsening book, price at or above the median P/NAV, price has not fallen behind peers. Long candidate: clean, stable book, price in the cheapest 30%. Deteriorating priced: worsening but already discounted. Cheap but messy: discounted with a poor book.',
  recon: 'Our sum of loan fair values divided by the total the BDC itself reported. 1.00 is a perfect match. Outside 0.90 to 1.10 the period is excluded from scores.',
  late_marks: 'Of loans the lender carried at 97 or better, the share that went bad within a year. The mark gave no warning.',
  early_warning: 'Of loans placed on non-accrual, the share already marked below 95 the quarter before. The mark did warn.',
  went_bad: 'Share of loan-quarters that went on non-accrual, below 80, or exited at a loss within four quarters.',
  loss_exit: 'Cost of loans that left the portfolio with a last mark below 90, per year, as a share of the average debt book. Likely sold cheap or written off.',
  first_lien: 'First in line to be repaid if the company fails. Safest loan type. Second lien is behind it; subordinated behind that. Preferred and common equity are ownership, paid last.',
  migration: 'Where each dollar of debt moved between mark buckets from last quarter to this one. Red cells are moves to a worse bucket.',
  vintage: 'The first quarter we saw the loan. Our history starts late 2022, so that vintage includes everything older.',
}
